/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.boxinggame2;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ap_icon=0x7f020000;
        public static final int ap_used_icon=0x7f020001;
        public static final int basic_block=0x7f020002;
        public static final int drop_line=0x7f020003;
        public static final int drop_line_entered=0x7f020004;
        public static final int fire_kick=0x7f020005;
        public static final int freeze=0x7f020006;
        public static final int hard_punch=0x7f020007;
        public static final int ic_launcher=0x7f020008;
        public static final int leg_grab=0x7f020009;
        public static final int mega_punch=0x7f02000a;
        public static final int quick_punch=0x7f02000b;
        public static final int round_kick=0x7f02000c;
    }
    public static final class id {
        public static final int action_settings=0x7f05001c;
        public static final int basic_block=0x7f050013;
        public static final int btnKungLao=0x7f05001a;
        public static final int btnScorpion=0x7f050018;
        public static final int btnSonya=0x7f05001b;
        public static final int btnSubZero=0x7f050019;
        public static final int end_turn=0x7f050002;
        public static final int first_player_action_line=0x7f050011;
        public static final int first_player_fire_kick=0x7f050006;
        public static final int first_player_freeze=0x7f050007;
        public static final int first_player_hard_punch=0x7f050004;
        public static final int first_player_health=0x7f050000;
        public static final int first_player_leg_grab=0x7f050009;
        public static final int first_player_mega_punch=0x7f050005;
        public static final int first_player_quick_punch=0x7f050003;
        public static final int first_player_round_kick=0x7f050008;
        public static final int llAP_icons_player1=0x7f050015;
        public static final int llAP_icons_player2=0x7f050017;
        public static final int player1Layout=0x7f050014;
        public static final int player2Layout=0x7f050016;
        public static final int second_player_action_line=0x7f050012;
        public static final int second_player_fire_kick=0x7f05000d;
        public static final int second_player_freeze=0x7f05000e;
        public static final int second_player_hard_punch=0x7f05000b;
        public static final int second_player_health=0x7f050001;
        public static final int second_player_leg_grab=0x7f050010;
        public static final int second_player_mega_punch=0x7f05000c;
        public static final int second_player_quick_punch=0x7f05000a;
        public static final int second_player_round_kick=0x7f05000f;
    }
    public static final class layout {
        public static final int activity_fight=0x7f030000;
        public static final int choose_fighter=0x7f030001;
    }
    public static final class menu {
        public static final int fight=0x7f080000;
    }
    public static final class string {
        public static final int KungLao=0x7f060009;
        public static final int Scorpion=0x7f060007;
        public static final int Sonya=0x7f06000a;
        public static final int SubZero=0x7f060008;
        public static final int action_icon_unused=0x7f060004;
        public static final int action_settings=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int choose_fighter=0x7f06000b;
        public static final int end_turn=0x7f060005;
        public static final int hardPunch=0x7f060006;
        public static final int hello_world=0x7f060002;
        public static final int quickPunch=0x7f060003;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
